### GET all scholars
GET http://localhost:5000/api/scholars
Accept: application/json

###

### GET a scholar by ID
GET http://localhost:3000/api/scholars/<_id_here>
Accept: application/json

###

### CREATE a new scholar
POST http://localhost:3000/api/scholars
Content-Type: application/json

{
  "scholarID": "N002",
  "fullname": "Josh Ticot",
  "picture": "https://example.com/joshh.jpg",
  "status": "active",
  "degreeProgram": "BS Computer Science",
  "yearLevel": 3,
  "contactNo": "09998887886"
}

###

### UPDATE a scholar by ID
PUT http://localhost:3000/api/scholars/<_id_here>
Content-Type: application/json

{
  "fullname": "Jane Smith",
  "status": "graduate",
  "yearLevel": 4
}

###

### DELETE a scholar by ID
DELETE http://localhost:3000/api/scholars/<_id_here>
Accept: application/json
